### ISSUE TITLE
Multi-line alias description possible

### ISSUE THREAD

**Issue by zPiste** [anonaddy/addy-ios#15] opened 2024-11-17 22:23 UTC
**Describe the bug**
When setting/editing the description of any alias inside the app, you can use multiple lines, which is not possible on the web app of addy. 

**To Reproduce**
1. Go to 'Aliases'
2. Click on any alias
3. Click on 'Description'
4. Here you can enter a description with multiple lines

**Expected behavior**
The description should be a single-line description, as you can't enter a multi-line description on the web app as well.

**Screenshots**
![Screenshot of the iOS app](https://github.com/user-attachments/assets/e693d073-328d-43da-a7db-1b803836a270)
Multi-line description possible
![Screenshot of the web app](https://github.com/user-attachments/assets/6f11787b-2d0b-4ca3-abfa-d76c593b298a)
Multi-line description not possible

**Desktop:**
 - OS: Windows 11
 - Chrome
 - v1.3.0

**Smartphone:**
 - Device: iPhone 13 Pro
 - OS: iOS 18.1
 - App v1.1.3

**Comment by Stjin** [comment] 2024-11-18 08:59
Hi,

Thanks for your report and close attention to detail! 

I have discussed with Will. The database and API allow for a TEXT type input, this includes multi-line text. Users who would like to use multiple lines are able to through the mobile apps for now (maybe this change will come to web in the future, but no definitive plans). Multiple lines entered in the app are still all visible in the web app.

Since there might be users who do use multiple lines I won't change this behaviour in the mobile app(s)

Closing this issue as "expected behaviour"

**Closed by Stjin** 2024-11-18 08:59 UTC
